### PR TITLE
Suppress info flags when -o -

### PR DESCRIPTION
**Pull request by snan**
as per documentation.

### CODE REVIEW

**Comment by snan** [comment]
Since the documentation says


      -o, --output string          Output path, for when there is only one URL.
                                   '-' means stdout and implies --quiet.
                                   It overrides --directory.

**Comment by makew0rld** [comment]
Huh, thanks. Let me know if you'd like a release.

**Comment by snan** [comment]
Sure, that'd be great.

**Comment by makew0rld** [comment]
Release made and binaries building now.

**Pull request merged**
